start java -cp soapServer_HoldersNoAttachment\src\build\classes noattachment.holders.soapserver.TestService_TestServicePort_Server
start java -cp soapServer_Mime\src\build\classes mime.soapserver.TestService_TestServicePort_Server
start java -cp soapServer_noHolders\src\build\classes noholders.soapserver.TestService_TestServicePort_Server
start java -cp soapServer_noMime\src\build\classes nomime.soapserver.TestService_TestServicePort_Server