package noattachment.holders.soapserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-03-13T16:47:06.425-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://soapserver.holders.noattachment/", name = "TestService")
@XmlSeeAlso({ObjectFactory.class})
public interface TestService {

    @RequestWrapper(localName = "serviceMethod", targetNamespace = "http://soapserver.holders.noattachment/", className = "noattachment.holders.soapserver.ServiceMethodRequest")
    @WebMethod
    @ResponseWrapper(localName = "serviceMethodResponse", targetNamespace = "http://soapserver.holders.noattachment/", className = "noattachment.holders.soapserver.ServiceMethodResponse")
    public void serviceMethod(
        @WebParam(name = "intA", targetNamespace = "")
        java.lang.Integer intA,
        @WebParam(mode = WebParam.Mode.OUT, name = "response", targetNamespace = "")
        javax.xml.ws.Holder<ServiceResponse> response,
        @WebParam(mode = WebParam.Mode.OUT, name = "attachment", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> attachment
    );
}
