
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package noholders.soapserver;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-09T15:52:25.594-08:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "TestServiceServicePorts",
                      portName = "TestServicePort",
                      targetNamespace = "http://soapserver.noholders/",
                      wsdlLocation = "testServiceNoHolders.wsdl",
                      endpointInterface = "noholders.soapserver.TestService")
                      
public class TestServiceImpl implements TestService {

    private static final Logger LOG = Logger.getLogger(TestServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see noholders.soapserver.TestService#serviceMethod(noholders.soapserver.ServiceMethodRequest  inputParameters )*
     */
    public noholders.soapserver.ServiceMethodResponse serviceMethod(ServiceMethodRequest inputParameters) { 
        LOG.info("Executing operation serviceMethod");
        System.out.println(inputParameters);
        try {
            noholders.soapserver.ServiceMethodResponse myServiceMethodResponse = new noholders.soapserver.ServiceMethodResponse();
            noholders.soapserver.ServiceResponse myServiceResponse = new noholders.soapserver.ServiceResponse();
            myServiceResponse.setMyInt(inputParameters.getIntA());
            myServiceResponse.setMyBool(true);
            myServiceMethodResponse.setResponse(myServiceResponse);
            myServiceMethodResponse.setAttachment((new String("Hello there")).getBytes());
            return myServiceMethodResponse;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
