package mime.soapserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-03-13T16:12:25.295-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://soapserver.mime/", name = "TestService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TestService {

    @WebMethod
    public void serviceMethod(
        @WebParam(partName = "inputParameters", name = "serviceMethodRequest", targetNamespace = "http://soapserver.mime/")
        ServiceMethodRequest inputParameters,
        @WebParam(partName = "outputParameters", mode = WebParam.Mode.OUT, name = "serviceMethodResponse", targetNamespace = "http://soapserver.mime/")
        javax.xml.ws.Holder<ServiceMethodResponse> outputParameters,
        @WebParam(partName = "attachment", mode = WebParam.Mode.OUT, name = "attachment", targetNamespace = "http://soapserver.mime/")
        javax.xml.ws.Holder<byte[]> attachment
    );
}
