
package noattachment.holders.soapserver;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-09T15:48:56.566-08:00
 * Generated source version: 2.5.2
 * 
 */
 
public class TestService_TestServicePort_Server{
    static String address = "http://localhost:8083/soapServerHoldersNoAttachment/services/test";

    protected TestService_TestServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new TestServiceImpl();
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        System.out.println("Deploying Service at: " + address);
        new TestService_TestServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(60 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
