
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package noattachment.holders.soapserver;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-09T15:48:56.527-08:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "TestServiceServicePorts",
                      portName = "TestServicePort",
                      targetNamespace = "http://soapserver.holders.noattachment/",
                      wsdlLocation = "testServiceHolderNoAttachments.wsdl",
                      endpointInterface = "noattachment.holders.soapserver.TestService")
                      
public class TestServiceImpl implements TestService {

    private static final Logger LOG = Logger.getLogger(TestServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see noattachment.holders.soapserver.TestService#serviceMethod(java.lang.Integer  intA ,)noattachment.holders.soapserver.ServiceResponse  response ,)byte[]  attachment )*
     */
    public void serviceMethod(java.lang.Integer intA,javax.xml.ws.Holder<ServiceResponse> response,javax.xml.ws.Holder<byte[]> attachment) { 
        LOG.info("Executing operation serviceMethod");
        System.out.println(intA);
        try {
            noattachment.holders.soapserver.ServiceResponse responseValue = new noattachment.holders.soapserver.ServiceResponse();
            responseValue.setMyInt(intA + 1);
            responseValue.setMyBool(true);
            response.value = responseValue;
            byte[] attachmentValue = (new String("Hello there")).getBytes();
            attachment.value = attachmentValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
